language: julia
os:
  - linux
  - osx

julia:
  - 1
  - 1.0

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 99999999

after_success:
  # push coverage results to Coveralls Pkg.test("ClinicalTrialUtilities"; coverage = true);
  - julia -e 'using Pkg; cd(Pkg.dir("Metida")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Metida")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  allow_failures:
    - os:
        - osx
    - julia:
        - 1.0
